import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300" , "400" , "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lato.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {process.env.NODE_ENV !== 'development' && (
          <GoogleAnalytics gaId="G-LWG1WRXZP5" />
        )}
      </body>
    </html>
  );
}
